// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: items.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    name,
    date,
    quantity,
    unit_price,
    line_total,
    receipt_id,
    seller_id,
    venue_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, date, quantity, unit_price, line_total, receipt_id, seller_id, venue_id
`

type CreateItemParams struct {
	Name      string
	Date      pgtype.Timestamp
	Quantity  string
	UnitPrice string
	LineTotal pgtype.Numeric
	ReceiptID string
	SellerID  int
	VenueID   int
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Date,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
		arg.ReceiptID,
		arg.SellerID,
		arg.VenueID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.ReceiptID,
		&i.SellerID,
		&i.VenueID,
	)
	return i, err
}
