// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID        int
	Name      string
	Date      pgtype.Timestamp
	Quantity  string
	UnitPrice string
	LineTotal pgtype.Numeric
	ReceiptID string
	SellerID  int
	VenueID   int
}

type Receipt struct {
	ID       string
	Date     pgtype.Timestamp
	SellerID int
	VenueID  int
	Total    pgtype.Numeric
	Tips     pgtype.Numeric
}

type Seller struct {
	ID   int
	Name string
}

type Venue struct {
	ID       int
	Name     string
	SellerID pgtype.Int4
}
